/**
 * Question Type Registry
 *
 * Central registry for all question types with:
 * - Metadata (display name, category, icon, etc.)
 * - Default attribute values
 * - Attribute schemas for the editor UI
 * - Factory functions for creating new questions
 * - Validation functions
 */

import { randomBytes } from 'crypto';

// Generate a unique ID similar to UUID v4
const generateId = () => randomBytes(16).toString('hex');
import {
  QuestionTypeId,
  QuestionCategory,
  QuestionTypeMetadata,
  QuestionTypeRegistryEntry,
  Question,
  AttributeSchema,
  ValidationResult,
  ShortTextQuestion,
  LongTextQuestion,
  NumberQuestion,
  EmailQuestion,
  PhoneQuestion,
  UrlQuestion,
  MultipleChoiceQuestion,
  CheckboxesQuestion,
  DropdownQuestion,
  YesNoQuestion,
  RatingQuestion,
  ScaleQuestion,
  SliderQuestion,
  NpsQuestion,
  OpinionScaleQuestion,
  DateQuestion,
  TimeQuestion,
  DateTimeQuestion,
  FileUploadQuestion,
  ImageUploadQuestion,
  SignatureQuestion,
  MatrixQuestion,
  RankingQuestion,
  AddressQuestion,
  TagsQuestion,
  ColorPickerQuestion,
  PaymentQuestion,
  ChoiceOption,
} from '@/types/questionTypes';

// ============================================
// Default Attribute Values
// ============================================

export const defaultAttributes = {
  short_text: {
    maxLength: 255,
    showCharacterCount: false,
    inputMask: undefined,
    autoCapitalize: 'sentences' as const,
    spellcheck: true,
    autocomplete: undefined,
  },

  long_text: {
    minLength: 0,
    maxLength: 5000,
    rows: 4,
    autoResize: true,
    showCharacterCount: true,
    richText: false,
    spellcheck: true,
  },

  number: {
    min: undefined,
    max: undefined,
    step: 1,
    decimalPlaces: 0,
    format: 'number' as const,
    currencyCode: 'USD',
    showStepper: false,
    useThousandSeparator: true,
    prefix: undefined,
    suffix: undefined,
  },

  email: {
    allowMultiple: false,
    validateFormat: true,
    blockDisposable: false,
    allowedDomains: [],
    blockedDomains: [],
    confirmEmail: false,
  },

  phone: {
    defaultCountry: 'US',
    showCountrySelector: true,
    allowedCountries: [],
    format: 'national' as const,
    validateFormat: true,
  },

  url: {
    requireHttps: false,
    validateFormat: true,
    allowedProtocols: ['http', 'https'],
    showPreview: false,
  },

  multiple_choice: {
    options: [
      { id: '1', label: 'Option 1', value: 'option_1' },
      { id: '2', label: 'Option 2', value: 'option_2' },
      { id: '3', label: 'Option 3', value: 'option_3' },
    ] as ChoiceOption[],
    layout: 'vertical' as const,
    columns: 2,
    randomize: false,
    allowOther: false,
    otherLabel: 'Other',
    showImages: false,
    imageSize: 'medium' as const,
  },

  checkboxes: {
    options: [
      { id: '1', label: 'Option 1', value: 'option_1' },
      { id: '2', label: 'Option 2', value: 'option_2' },
      { id: '3', label: 'Option 3', value: 'option_3' },
    ] as ChoiceOption[],
    layout: 'vertical' as const,
    columns: 2,
    randomize: false,
    allowOther: false,
    otherLabel: 'Other',
    minSelections: 0,
    maxSelections: undefined,
    showSelectAll: false,
  },

  dropdown: {
    options: [
      { id: '1', label: 'Option 1', value: 'option_1' },
      { id: '2', label: 'Option 2', value: 'option_2' },
      { id: '3', label: 'Option 3', value: 'option_3' },
    ] as ChoiceOption[],
    multiple: false,
    searchable: true,
    allowCreate: false,
    grouped: false,
    groups: undefined,
    clearable: true,
    loadingText: 'Loading...',
    noOptionsText: 'No options available',
    lookup: undefined,
  },

  yes_no: {
    style: 'toggle' as const,
    yesLabel: 'Yes',
    noLabel: 'No',
    defaultValue: undefined,
    valueType: 'boolean' as const,
  },

  rating: {
    maxRating: 5,
    iconType: 'star' as const,
    customIcons: undefined,
    iconSize: 'medium' as const,
    showLabels: false,
    labels: undefined,
    allowHalf: false,
    showHoverPreview: true,
    activeColor: '#FFD700',
    inactiveColor: '#E0E0E0',
  },

  scale: {
    minValue: 1,
    maxValue: 10,
    step: 1,
    lowLabel: 'Not at all likely',
    highLabel: 'Extremely likely',
    middleLabel: undefined,
    showValueLabels: true,
    valueLabels: undefined,
    displayStyle: 'buttons' as const,
  },

  slider: {
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 50,
    showTicks: false,
    tickInterval: 10,
    showValue: true,
    valuePosition: 'tooltip' as const,
    showMinMax: true,
    marks: undefined,
    trackColor: '#00ED64',
    range: false,
  },

  nps: {
    detractorLabel: 'Not likely',
    passiveLabel: 'Neutral',
    promoterLabel: 'Very likely',
    showCategoryLabels: true,
    showExplanation: true,
    detractorFollowUp: undefined,
    promoterFollowUp: undefined,
    useColorCoding: true,
  },

  opinion_scale: {
    options: [
      { value: 1, label: 'Strongly Disagree', emoji: '😠' },
      { value: 2, label: 'Disagree', emoji: '🙁' },
      { value: 3, label: 'Neutral', emoji: '😐' },
      { value: 4, label: 'Agree', emoji: '🙂' },
      { value: 5, label: 'Strongly Agree', emoji: '😄' },
    ],
    showNeutral: true,
    neutralLabel: 'Neutral',
    displayStyle: 'buttons' as const,
    scaleType: 'agreement' as const,
  },

  date: {
    displayFormat: 'MM/DD/YYYY',
    storageFormat: 'iso' as const,
    minDate: undefined,
    maxDate: undefined,
    disabledDates: undefined,
    disableWeekends: false,
    disablePast: false,
    disableFuture: false,
    showWeekNumbers: false,
    firstDayOfWeek: 0,
    range: false,
    pickerStyle: 'calendar' as const,
  },

  time: {
    format: '12h' as const,
    minuteStep: 15,
    minTime: undefined,
    maxTime: undefined,
    showSeconds: false,
    pickerStyle: 'dropdown' as const,
  },

  datetime: {
    dateFormat: 'MM/DD/YYYY',
    timeFormat: '12h' as const,
    storageFormat: 'iso' as const,
    timezone: 'local' as const,
    customTimezone: undefined,
    showTimezoneSelector: false,
    minDateTime: undefined,
    maxDateTime: undefined,
    minuteStep: 15,
  },

  file_upload: {
    allowedTypes: ['*/*'],
    maxFileSize: 10 * 1024 * 1024, // 10MB
    multiple: false,
    maxFiles: 1,
    showPreview: true,
    dragDrop: true,
    uploadButtonText: 'Choose File',
    showProgress: true,
    acceptDescription: 'All files accepted',
  },

  image_upload: {
    allowedTypes: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
    maxFileSize: 5 * 1024 * 1024, // 5MB
    multiple: false,
    maxImages: 1,
    enableCrop: false,
    cropAspectRatio: undefined,
    minDimensions: undefined,
    maxDimensions: undefined,
    showPreview: true,
    previewSize: 'medium' as const,
    compress: false,
    compressionQuality: 0.8,
  },

  signature: {
    canvasWidth: 400,
    canvasHeight: 200,
    strokeColor: '#000000',
    strokeWidth: 2,
    backgroundColor: '#FFFFFF',
    showClear: true,
    allowTyped: true,
    outputFormat: 'png' as const,
  },

  matrix: {
    rows: [
      { id: 'row1', label: 'Row 1' },
      { id: 'row2', label: 'Row 2' },
      { id: 'row3', label: 'Row 3' },
    ],
    columns: [
      { id: 'col1', label: 'Column 1' },
      { id: 'col2', label: 'Column 2' },
      { id: 'col3', label: 'Column 3' },
    ],
    cellType: 'radio' as const,
    dropdownOptions: undefined,
    requireAllRows: true,
    onePerColumn: false,
    randomizeRows: false,
    randomizeColumns: false,
    mobileLayout: 'stack' as const,
    alternateRowColors: true,
  },

  ranking: {
    items: [
      { id: '1', label: 'Item 1' },
      { id: '2', label: 'Item 2' },
      { id: '3', label: 'Item 3' },
    ],
    minRank: 0,
    maxRank: 0,
    showRankNumbers: true,
    dragStyle: 'list' as const,
    showImages: false,
    randomize: false,
    allowTies: false,
  },

  address: {
    components: ['street1', 'city', 'state', 'postalCode', 'country'] as readonly string[],
    defaultCountry: 'US',
    autocomplete: true,
    autocompleteProvider: undefined,
    showMap: false,
    requireAll: true,
    allowedCountries: [],
    displayMode: 'multi' as const,
  },

  tags: {
    suggestions: [],
    allowCustom: true,
    minTags: 0,
    maxTags: 10,
    maxTagLength: 50,
    validationPattern: undefined,
    showSuggestions: true,
    createOnEnter: true,
    createOnComma: true,
    caseHandling: 'lowercase' as const,
  },

  color_picker: {
    defaultColor: '#000000',
    format: 'hex' as const,
    showAlpha: false,
    presetColors: ['#FF0000', '#00FF00', '#0000FF', '#FFFF00', '#FF00FF', '#00FFFF'],
    presetsOnly: false,
    pickerStyle: 'chrome' as const,
  },

  payment: {
    provider: 'stripe' as const,
    currency: 'USD',
    amountType: 'fixed' as const,
    fixedAmount: undefined,
    minAmount: 1,
    maxAmount: 10000,
    presetAmounts: [10, 25, 50, 100],
    allowCustomAmount: true,
    showCurrencySymbol: true,
    subscriptionPlans: undefined,
  },
};

// ============================================
// Attribute Schemas for Editor UI
// ============================================

/**
 * Generate attribute schemas for each question type
 * These define how the attribute editor renders controls
 */
export const attributeSchemas: Record<QuestionTypeId, AttributeSchema[]> = {
  short_text: [
    {
      name: 'maxLength',
      label: 'Maximum Length',
      description: 'Maximum number of characters allowed',
      dataType: 'number',
      defaultValue: 255,
      controlType: 'number_input',
      validation: { min: 1, max: 10000 },
      group: 'validation',
      order: 1,
    },
    {
      name: 'showCharacterCount',
      label: 'Show Character Count',
      description: 'Display remaining characters',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'appearance',
      order: 1,
    },
    {
      name: 'inputMask',
      label: 'Input Mask',
      description: 'Format pattern (e.g., phone, SSN)',
      dataType: 'string',
      defaultValue: '',
      controlType: 'dropdown',
      options: [
        { value: '', label: 'None' },
        { value: 'phone', label: 'Phone Number' },
        { value: 'ssn', label: 'SSN' },
        { value: 'credit-card', label: 'Credit Card' },
        { value: 'zip', label: 'ZIP Code' },
      ],
      group: 'behavior',
      order: 1,
    },
    {
      name: 'autoCapitalize',
      label: 'Auto Capitalize',
      dataType: 'string',
      defaultValue: 'sentences',
      controlType: 'dropdown',
      options: [
        { value: 'none', label: 'None' },
        { value: 'sentences', label: 'Sentences' },
        { value: 'words', label: 'Words' },
        { value: 'characters', label: 'All Characters' },
      ],
      group: 'behavior',
      order: 2,
    },
    {
      name: 'spellcheck',
      label: 'Enable Spellcheck',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'behavior',
      order: 3,
    },
    {
      name: 'autocomplete',
      label: 'Autocomplete Hint',
      description: 'Browser autocomplete suggestion',
      dataType: 'string',
      defaultValue: '',
      controlType: 'dropdown',
      options: [
        { value: '', label: 'None' },
        { value: 'name', label: 'Name' },
        { value: 'given-name', label: 'First Name' },
        { value: 'family-name', label: 'Last Name' },
        { value: 'organization', label: 'Organization' },
        { value: 'street-address', label: 'Street Address' },
        { value: 'postal-code', label: 'Postal Code' },
      ],
      group: 'behavior',
      order: 4,
    },
  ],

  long_text: [
    {
      name: 'minLength',
      label: 'Minimum Length',
      dataType: 'number',
      defaultValue: 0,
      controlType: 'number_input',
      validation: { min: 0 },
      group: 'validation',
      order: 1,
    },
    {
      name: 'maxLength',
      label: 'Maximum Length',
      dataType: 'number',
      defaultValue: 5000,
      controlType: 'number_input',
      validation: { min: 1, max: 100000 },
      group: 'validation',
      order: 2,
    },
    {
      name: 'rows',
      label: 'Visible Rows',
      dataType: 'number',
      defaultValue: 4,
      controlType: 'slider',
      validation: { min: 2, max: 20 },
      group: 'appearance',
      order: 1,
    },
    {
      name: 'autoResize',
      label: 'Auto Resize',
      description: 'Expand as user types',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 2,
    },
    {
      name: 'showCharacterCount',
      label: 'Show Character Count',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'richText',
      label: 'Rich Text Editor',
      description: 'Enable formatting toolbar',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'advanced',
      order: 1,
    },
  ],

  number: [
    {
      name: 'min',
      label: 'Minimum Value',
      dataType: 'number',
      defaultValue: undefined,
      controlType: 'number_input',
      group: 'validation',
      order: 1,
    },
    {
      name: 'max',
      label: 'Maximum Value',
      dataType: 'number',
      defaultValue: undefined,
      controlType: 'number_input',
      group: 'validation',
      order: 2,
    },
    {
      name: 'step',
      label: 'Step',
      description: 'Increment value',
      dataType: 'number',
      defaultValue: 1,
      controlType: 'number_input',
      validation: { min: 0.001 },
      group: 'validation',
      order: 3,
    },
    {
      name: 'decimalPlaces',
      label: 'Decimal Places',
      dataType: 'number',
      defaultValue: 0,
      controlType: 'number_input',
      validation: { min: 0, max: 10 },
      group: 'appearance',
      order: 1,
    },
    {
      name: 'format',
      label: 'Display Format',
      dataType: 'string',
      defaultValue: 'number',
      controlType: 'dropdown',
      options: [
        { value: 'number', label: 'Number' },
        { value: 'currency', label: 'Currency' },
        { value: 'percentage', label: 'Percentage' },
      ],
      group: 'appearance',
      order: 2,
    },
    {
      name: 'currencyCode',
      label: 'Currency',
      dataType: 'string',
      defaultValue: 'USD',
      controlType: 'dropdown',
      options: [
        { value: 'USD', label: 'USD ($)' },
        { value: 'EUR', label: 'EUR (€)' },
        { value: 'GBP', label: 'GBP (£)' },
        { value: 'JPY', label: 'JPY (¥)' },
        { value: 'CAD', label: 'CAD ($)' },
        { value: 'AUD', label: 'AUD ($)' },
      ],
      showWhen: { attribute: 'format', operator: 'equals', value: 'currency' },
      group: 'appearance',
      order: 3,
    },
    {
      name: 'showStepper',
      label: 'Show +/- Buttons',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'appearance',
      order: 4,
    },
    {
      name: 'useThousandSeparator',
      label: 'Thousand Separator',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 5,
    },
    {
      name: 'prefix',
      label: 'Prefix',
      description: 'Text before number',
      dataType: 'string',
      defaultValue: '',
      controlType: 'text_input',
      group: 'appearance',
      order: 6,
    },
    {
      name: 'suffix',
      label: 'Suffix',
      description: 'Text after number',
      dataType: 'string',
      defaultValue: '',
      controlType: 'text_input',
      group: 'appearance',
      order: 7,
    },
  ],

  email: [
    {
      name: 'validateFormat',
      label: 'Validate Format',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'validation',
      order: 1,
    },
    {
      name: 'allowMultiple',
      label: 'Allow Multiple Emails',
      description: 'Comma-separated emails',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 1,
    },
    {
      name: 'confirmEmail',
      label: 'Require Confirmation',
      description: 'Add confirmation field',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 2,
    },
    {
      name: 'blockDisposable',
      label: 'Block Disposable Emails',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'advanced',
      order: 1,
    },
    {
      name: 'allowedDomains',
      label: 'Allowed Domains',
      description: 'Leave empty for all',
      dataType: 'array',
      defaultValue: [],
      controlType: 'key_value_editor',
      group: 'advanced',
      order: 2,
    },
    {
      name: 'blockedDomains',
      label: 'Blocked Domains',
      dataType: 'array',
      defaultValue: [],
      controlType: 'key_value_editor',
      group: 'advanced',
      order: 3,
    },
  ],

  phone: [
    {
      name: 'defaultCountry',
      label: 'Default Country',
      dataType: 'string',
      defaultValue: 'US',
      controlType: 'dropdown',
      options: [
        { value: 'US', label: 'United States' },
        { value: 'GB', label: 'United Kingdom' },
        { value: 'CA', label: 'Canada' },
        { value: 'AU', label: 'Australia' },
        { value: 'DE', label: 'Germany' },
        { value: 'FR', label: 'France' },
      ],
      group: 'basic',
      order: 1,
    },
    {
      name: 'showCountrySelector',
      label: 'Show Country Selector',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 1,
    },
    {
      name: 'format',
      label: 'Display Format',
      dataType: 'string',
      defaultValue: 'national',
      controlType: 'dropdown',
      options: [
        { value: 'national', label: 'National (555) 123-4567' },
        { value: 'international', label: 'International +1 555 123 4567' },
        { value: 'e164', label: 'E.164 +15551234567' },
      ],
      group: 'appearance',
      order: 2,
    },
    {
      name: 'validateFormat',
      label: 'Validate Format',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'validation',
      order: 1,
    },
  ],

  url: [
    {
      name: 'validateFormat',
      label: 'Validate Format',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'validation',
      order: 1,
    },
    {
      name: 'requireHttps',
      label: 'Require HTTPS',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'validation',
      order: 2,
    },
    {
      name: 'allowedProtocols',
      label: 'Allowed Protocols',
      dataType: 'array',
      defaultValue: ['http', 'https'],
      controlType: 'multi_select',
      options: [
        { value: 'http', label: 'HTTP' },
        { value: 'https', label: 'HTTPS' },
        { value: 'ftp', label: 'FTP' },
        { value: 'mailto', label: 'Mailto' },
      ],
      group: 'validation',
      order: 3,
    },
    {
      name: 'showPreview',
      label: 'Show Link Preview',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'appearance',
      order: 1,
    },
  ],

  multiple_choice: [
    {
      name: 'options',
      label: 'Options',
      dataType: 'array',
      defaultValue: [],
      controlType: 'option_list_editor',
      group: 'basic',
      order: 1,
    },
    {
      name: 'layout',
      label: 'Layout',
      dataType: 'string',
      defaultValue: 'vertical',
      controlType: 'dropdown',
      options: [
        { value: 'vertical', label: 'Vertical' },
        { value: 'horizontal', label: 'Horizontal' },
        { value: 'grid', label: 'Grid' },
      ],
      group: 'appearance',
      order: 1,
    },
    {
      name: 'columns',
      label: 'Columns',
      dataType: 'number',
      defaultValue: 2,
      controlType: 'number_input',
      validation: { min: 1, max: 6 },
      showWhen: { attribute: 'layout', operator: 'equals', value: 'grid' },
      group: 'appearance',
      order: 2,
    },
    {
      name: 'randomize',
      label: 'Randomize Order',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 1,
    },
    {
      name: 'allowOther',
      label: 'Allow "Other" Option',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 2,
    },
    {
      name: 'otherLabel',
      label: '"Other" Label',
      dataType: 'string',
      defaultValue: 'Other',
      controlType: 'text_input',
      showWhen: { attribute: 'allowOther', operator: 'equals', value: true },
      group: 'behavior',
      order: 3,
    },
    {
      name: 'showImages',
      label: 'Show Images',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'imageSize',
      label: 'Image Size',
      dataType: 'string',
      defaultValue: 'medium',
      controlType: 'dropdown',
      options: [
        { value: 'small', label: 'Small' },
        { value: 'medium', label: 'Medium' },
        { value: 'large', label: 'Large' },
      ],
      showWhen: { attribute: 'showImages', operator: 'equals', value: true },
      group: 'appearance',
      order: 4,
    },
  ],

  checkboxes: [
    {
      name: 'options',
      label: 'Options',
      dataType: 'array',
      defaultValue: [],
      controlType: 'option_list_editor',
      group: 'basic',
      order: 1,
    },
    {
      name: 'layout',
      label: 'Layout',
      dataType: 'string',
      defaultValue: 'vertical',
      controlType: 'dropdown',
      options: [
        { value: 'vertical', label: 'Vertical' },
        { value: 'horizontal', label: 'Horizontal' },
        { value: 'grid', label: 'Grid' },
      ],
      group: 'appearance',
      order: 1,
    },
    {
      name: 'columns',
      label: 'Columns',
      dataType: 'number',
      defaultValue: 2,
      controlType: 'number_input',
      validation: { min: 1, max: 6 },
      showWhen: { attribute: 'layout', operator: 'equals', value: 'grid' },
      group: 'appearance',
      order: 2,
    },
    {
      name: 'minSelections',
      label: 'Minimum Selections',
      dataType: 'number',
      defaultValue: 0,
      controlType: 'number_input',
      validation: { min: 0 },
      group: 'validation',
      order: 1,
    },
    {
      name: 'maxSelections',
      label: 'Maximum Selections',
      description: 'Leave empty for unlimited',
      dataType: 'number',
      defaultValue: undefined,
      controlType: 'number_input',
      validation: { min: 1 },
      group: 'validation',
      order: 2,
    },
    {
      name: 'randomize',
      label: 'Randomize Order',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 1,
    },
    {
      name: 'showSelectAll',
      label: 'Show "Select All"',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 2,
    },
    {
      name: 'allowOther',
      label: 'Allow "Other" Option',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 3,
    },
    {
      name: 'otherLabel',
      label: '"Other" Label',
      dataType: 'string',
      defaultValue: 'Other',
      controlType: 'text_input',
      showWhen: { attribute: 'allowOther', operator: 'equals', value: true },
      group: 'behavior',
      order: 4,
    },
  ],

  dropdown: [
    {
      name: 'options',
      label: 'Options',
      dataType: 'array',
      defaultValue: [],
      controlType: 'option_list_editor',
      group: 'basic',
      order: 1,
    },
    {
      name: 'multiple',
      label: 'Allow Multiple',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 1,
    },
    {
      name: 'searchable',
      label: 'Searchable',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'behavior',
      order: 2,
    },
    {
      name: 'clearable',
      label: 'Clearable',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'behavior',
      order: 3,
    },
    {
      name: 'allowCreate',
      label: 'Allow Create New',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 4,
    },
    {
      name: 'noOptionsText',
      label: 'No Options Text',
      dataType: 'string',
      defaultValue: 'No options available',
      controlType: 'text_input',
      group: 'appearance',
      order: 1,
    },
    {
      name: 'loadingText',
      label: 'Loading Text',
      dataType: 'string',
      defaultValue: 'Loading...',
      controlType: 'text_input',
      group: 'appearance',
      order: 2,
    },
  ],

  yes_no: [
    {
      name: 'style',
      label: 'Display Style',
      dataType: 'string',
      defaultValue: 'toggle',
      controlType: 'dropdown',
      options: [
        { value: 'toggle', label: 'Toggle Switch' },
        { value: 'buttons', label: 'Buttons' },
        { value: 'radio', label: 'Radio Buttons' },
      ],
      group: 'appearance',
      order: 1,
    },
    {
      name: 'yesLabel',
      label: 'Yes Label',
      dataType: 'string',
      defaultValue: 'Yes',
      controlType: 'text_input',
      group: 'appearance',
      order: 2,
    },
    {
      name: 'noLabel',
      label: 'No Label',
      dataType: 'string',
      defaultValue: 'No',
      controlType: 'text_input',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'defaultValue',
      label: 'Default Value',
      dataType: 'boolean',
      defaultValue: undefined,
      controlType: 'dropdown',
      options: [
        { value: undefined, label: 'None' },
        { value: true, label: 'Yes' },
        { value: false, label: 'No' },
      ],
      group: 'behavior',
      order: 1,
    },
    {
      name: 'valueType',
      label: 'Storage Type',
      dataType: 'string',
      defaultValue: 'boolean',
      controlType: 'dropdown',
      options: [
        { value: 'boolean', label: 'Boolean (true/false)' },
        { value: 'string', label: 'String ("yes"/"no")' },
      ],
      group: 'advanced',
      order: 1,
    },
  ],

  rating: [
    {
      name: 'maxRating',
      label: 'Maximum Rating',
      dataType: 'number',
      defaultValue: 5,
      controlType: 'number_input',
      validation: { min: 2, max: 10 },
      group: 'basic',
      order: 1,
    },
    {
      name: 'iconType',
      label: 'Icon Type',
      dataType: 'string',
      defaultValue: 'star',
      controlType: 'dropdown',
      options: [
        { value: 'star', label: '⭐ Stars' },
        { value: 'heart', label: '❤️ Hearts' },
        { value: 'thumb', label: '👍 Thumbs' },
        { value: 'emoji', label: '😊 Emojis' },
        { value: 'number', label: '123 Numbers' },
      ],
      group: 'appearance',
      order: 1,
    },
    {
      name: 'iconSize',
      label: 'Icon Size',
      dataType: 'string',
      defaultValue: 'medium',
      controlType: 'dropdown',
      options: [
        { value: 'small', label: 'Small' },
        { value: 'medium', label: 'Medium' },
        { value: 'large', label: 'Large' },
      ],
      group: 'appearance',
      order: 2,
    },
    {
      name: 'allowHalf',
      label: 'Allow Half Ratings',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 1,
    },
    {
      name: 'showLabels',
      label: 'Show Labels',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'showHoverPreview',
      label: 'Hover Preview',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'behavior',
      order: 2,
    },
    {
      name: 'activeColor',
      label: 'Active Color',
      dataType: 'string',
      defaultValue: '#FFD700',
      controlType: 'color_picker',
      group: 'appearance',
      order: 4,
    },
    {
      name: 'inactiveColor',
      label: 'Inactive Color',
      dataType: 'string',
      defaultValue: '#E0E0E0',
      controlType: 'color_picker',
      group: 'appearance',
      order: 5,
    },
  ],

  scale: [
    {
      name: 'minValue',
      label: 'Minimum Value',
      dataType: 'number',
      defaultValue: 1,
      controlType: 'number_input',
      validation: { min: 0, max: 100 },
      group: 'basic',
      order: 1,
    },
    {
      name: 'maxValue',
      label: 'Maximum Value',
      dataType: 'number',
      defaultValue: 10,
      controlType: 'number_input',
      validation: { min: 2, max: 100 },
      group: 'basic',
      order: 2,
    },
    {
      name: 'step',
      label: 'Step',
      dataType: 'number',
      defaultValue: 1,
      controlType: 'number_input',
      validation: { min: 1 },
      group: 'basic',
      order: 3,
    },
    {
      name: 'lowLabel',
      label: 'Low Label (Left)',
      dataType: 'string',
      defaultValue: 'Not at all likely',
      controlType: 'text_input',
      group: 'appearance',
      order: 1,
    },
    {
      name: 'highLabel',
      label: 'High Label (Right)',
      dataType: 'string',
      defaultValue: 'Extremely likely',
      controlType: 'text_input',
      group: 'appearance',
      order: 2,
    },
    {
      name: 'middleLabel',
      label: 'Middle Label (Optional)',
      dataType: 'string',
      defaultValue: '',
      controlType: 'text_input',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'showValueLabels',
      label: 'Show Value Labels',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 4,
    },
    {
      name: 'displayStyle',
      label: 'Display Style',
      dataType: 'string',
      defaultValue: 'buttons',
      controlType: 'dropdown',
      options: [
        { value: 'buttons', label: 'Buttons' },
        { value: 'slider', label: 'Slider' },
        { value: 'radio', label: 'Radio Buttons' },
      ],
      group: 'appearance',
      order: 5,
    },
  ],

  slider: [
    {
      name: 'min',
      label: 'Minimum',
      dataType: 'number',
      defaultValue: 0,
      controlType: 'number_input',
      group: 'basic',
      order: 1,
    },
    {
      name: 'max',
      label: 'Maximum',
      dataType: 'number',
      defaultValue: 100,
      controlType: 'number_input',
      group: 'basic',
      order: 2,
    },
    {
      name: 'step',
      label: 'Step',
      dataType: 'number',
      defaultValue: 1,
      controlType: 'number_input',
      validation: { min: 0.01 },
      group: 'basic',
      order: 3,
    },
    {
      name: 'defaultValue',
      label: 'Default Value',
      dataType: 'number',
      defaultValue: 50,
      controlType: 'number_input',
      group: 'basic',
      order: 4,
    },
    {
      name: 'showValue',
      label: 'Show Current Value',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 1,
    },
    {
      name: 'valuePosition',
      label: 'Value Position',
      dataType: 'string',
      defaultValue: 'tooltip',
      controlType: 'dropdown',
      options: [
        { value: 'above', label: 'Above' },
        { value: 'below', label: 'Below' },
        { value: 'tooltip', label: 'Tooltip' },
      ],
      showWhen: { attribute: 'showValue', operator: 'equals', value: true },
      group: 'appearance',
      order: 2,
    },
    {
      name: 'showMinMax',
      label: 'Show Min/Max Labels',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'showTicks',
      label: 'Show Tick Marks',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'appearance',
      order: 4,
    },
    {
      name: 'tickInterval',
      label: 'Tick Interval',
      dataType: 'number',
      defaultValue: 10,
      controlType: 'number_input',
      showWhen: { attribute: 'showTicks', operator: 'equals', value: true },
      group: 'appearance',
      order: 5,
    },
    {
      name: 'trackColor',
      label: 'Track Color',
      dataType: 'string',
      defaultValue: '#00ED64',
      controlType: 'color_picker',
      group: 'appearance',
      order: 6,
    },
    {
      name: 'range',
      label: 'Range Selection',
      description: 'Enable two handles for range',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 1,
    },
  ],

  nps: [
    {
      name: 'showCategoryLabels',
      label: 'Show Category Labels',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 1,
    },
    {
      name: 'detractorLabel',
      label: 'Detractor Label (0-6)',
      dataType: 'string',
      defaultValue: 'Not likely',
      controlType: 'text_input',
      group: 'appearance',
      order: 2,
    },
    {
      name: 'passiveLabel',
      label: 'Passive Label (7-8)',
      dataType: 'string',
      defaultValue: 'Neutral',
      controlType: 'text_input',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'promoterLabel',
      label: 'Promoter Label (9-10)',
      dataType: 'string',
      defaultValue: 'Very likely',
      controlType: 'text_input',
      group: 'appearance',
      order: 4,
    },
    {
      name: 'showExplanation',
      label: 'Show Score Explanation',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 5,
    },
    {
      name: 'useColorCoding',
      label: 'Use Color Coding',
      description: 'Red → Yellow → Green',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 6,
    },
    {
      name: 'detractorFollowUp',
      label: 'Detractor Follow-up',
      description: 'Question for 0-6 scores',
      dataType: 'string',
      defaultValue: '',
      controlType: 'textarea',
      group: 'behavior',
      order: 1,
    },
    {
      name: 'promoterFollowUp',
      label: 'Promoter Follow-up',
      description: 'Question for 9-10 scores',
      dataType: 'string',
      defaultValue: '',
      controlType: 'textarea',
      group: 'behavior',
      order: 2,
    },
  ],

  // Date & Time types
  date: [
    {
      name: 'displayFormat',
      label: 'Display Format',
      dataType: 'string',
      defaultValue: 'MM/DD/YYYY',
      controlType: 'dropdown',
      options: [
        { value: 'MM/DD/YYYY', label: 'MM/DD/YYYY' },
        { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY' },
        { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD' },
        { value: 'MMM DD, YYYY', label: 'MMM DD, YYYY' },
        { value: 'MMMM DD, YYYY', label: 'MMMM DD, YYYY' },
      ],
      group: 'appearance',
      order: 1,
    },
    {
      name: 'storageFormat',
      label: 'Storage Format',
      dataType: 'string',
      defaultValue: 'iso',
      controlType: 'dropdown',
      options: [
        { value: 'iso', label: 'ISO 8601' },
        { value: 'unix', label: 'Unix Timestamp' },
        { value: 'string', label: 'Formatted String' },
      ],
      group: 'advanced',
      order: 1,
    },
    {
      name: 'pickerStyle',
      label: 'Picker Style',
      dataType: 'string',
      defaultValue: 'calendar',
      controlType: 'dropdown',
      options: [
        { value: 'calendar', label: 'Calendar Popup' },
        { value: 'input', label: 'Text Input' },
        { value: 'both', label: 'Both' },
      ],
      group: 'appearance',
      order: 2,
    },
    {
      name: 'disablePast',
      label: 'Disable Past Dates',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'validation',
      order: 1,
    },
    {
      name: 'disableFuture',
      label: 'Disable Future Dates',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'validation',
      order: 2,
    },
    {
      name: 'disableWeekends',
      label: 'Disable Weekends',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'validation',
      order: 3,
    },
    {
      name: 'range',
      label: 'Date Range Selection',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 1,
    },
    {
      name: 'firstDayOfWeek',
      label: 'First Day of Week',
      dataType: 'number',
      defaultValue: 0,
      controlType: 'dropdown',
      options: [
        { value: 0, label: 'Sunday' },
        { value: 1, label: 'Monday' },
        { value: 6, label: 'Saturday' },
      ],
      group: 'appearance',
      order: 3,
    },
    {
      name: 'showWeekNumbers',
      label: 'Show Week Numbers',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'appearance',
      order: 4,
    },
  ],

  time: [
    {
      name: 'format',
      label: 'Time Format',
      dataType: 'string',
      defaultValue: '12h',
      controlType: 'dropdown',
      options: [
        { value: '12h', label: '12-hour (AM/PM)' },
        { value: '24h', label: '24-hour' },
      ],
      group: 'appearance',
      order: 1,
    },
    {
      name: 'minuteStep',
      label: 'Minute Interval',
      dataType: 'number',
      defaultValue: 15,
      controlType: 'dropdown',
      options: [
        { value: 1, label: '1 minute' },
        { value: 5, label: '5 minutes' },
        { value: 10, label: '10 minutes' },
        { value: 15, label: '15 minutes' },
        { value: 30, label: '30 minutes' },
        { value: 60, label: '1 hour' },
      ],
      group: 'behavior',
      order: 1,
    },
    {
      name: 'pickerStyle',
      label: 'Picker Style',
      dataType: 'string',
      defaultValue: 'dropdown',
      controlType: 'dropdown',
      options: [
        { value: 'clock', label: 'Clock' },
        { value: 'dropdown', label: 'Dropdown' },
        { value: 'input', label: 'Text Input' },
      ],
      group: 'appearance',
      order: 2,
    },
    {
      name: 'showSeconds',
      label: 'Show Seconds',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'minTime',
      label: 'Minimum Time',
      dataType: 'string',
      defaultValue: '',
      controlType: 'time_picker',
      group: 'validation',
      order: 1,
    },
    {
      name: 'maxTime',
      label: 'Maximum Time',
      dataType: 'string',
      defaultValue: '',
      controlType: 'time_picker',
      group: 'validation',
      order: 2,
    },
  ],

  datetime: [
    {
      name: 'dateFormat',
      label: 'Date Format',
      dataType: 'string',
      defaultValue: 'MM/DD/YYYY',
      controlType: 'dropdown',
      options: [
        { value: 'MM/DD/YYYY', label: 'MM/DD/YYYY' },
        { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY' },
        { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD' },
      ],
      group: 'appearance',
      order: 1,
    },
    {
      name: 'timeFormat',
      label: 'Time Format',
      dataType: 'string',
      defaultValue: '12h',
      controlType: 'dropdown',
      options: [
        { value: '12h', label: '12-hour (AM/PM)' },
        { value: '24h', label: '24-hour' },
      ],
      group: 'appearance',
      order: 2,
    },
    {
      name: 'minuteStep',
      label: 'Minute Interval',
      dataType: 'number',
      defaultValue: 15,
      controlType: 'dropdown',
      options: [
        { value: 5, label: '5 minutes' },
        { value: 15, label: '15 minutes' },
        { value: 30, label: '30 minutes' },
      ],
      group: 'behavior',
      order: 1,
    },
    {
      name: 'timezone',
      label: 'Timezone',
      dataType: 'string',
      defaultValue: 'local',
      controlType: 'dropdown',
      options: [
        { value: 'local', label: 'Local Time' },
        { value: 'utc', label: 'UTC' },
        { value: 'custom', label: 'Custom' },
      ],
      group: 'behavior',
      order: 2,
    },
    {
      name: 'showTimezoneSelector',
      label: 'Show Timezone Selector',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'storageFormat',
      label: 'Storage Format',
      dataType: 'string',
      defaultValue: 'iso',
      controlType: 'dropdown',
      options: [
        { value: 'iso', label: 'ISO 8601' },
        { value: 'unix', label: 'Unix Timestamp' },
      ],
      group: 'advanced',
      order: 1,
    },
  ],

  // File upload types
  file_upload: [
    {
      name: 'allowedTypes',
      label: 'Allowed File Types',
      dataType: 'array',
      defaultValue: ['*/*'],
      controlType: 'file_type_selector',
      group: 'validation',
      order: 1,
    },
    {
      name: 'maxFileSize',
      label: 'Max File Size (MB)',
      dataType: 'number',
      defaultValue: 10,
      controlType: 'number_input',
      validation: { min: 0.1, max: 100 },
      group: 'validation',
      order: 2,
    },
    {
      name: 'multiple',
      label: 'Allow Multiple Files',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 1,
    },
    {
      name: 'maxFiles',
      label: 'Maximum Files',
      dataType: 'number',
      defaultValue: 5,
      controlType: 'number_input',
      validation: { min: 1, max: 20 },
      showWhen: { attribute: 'multiple', operator: 'equals', value: true },
      group: 'behavior',
      order: 2,
    },
    {
      name: 'dragDrop',
      label: 'Enable Drag & Drop',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 1,
    },
    {
      name: 'showPreview',
      label: 'Show File Preview',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 2,
    },
    {
      name: 'showProgress',
      label: 'Show Upload Progress',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'uploadButtonText',
      label: 'Button Text',
      dataType: 'string',
      defaultValue: 'Choose File',
      controlType: 'text_input',
      group: 'appearance',
      order: 4,
    },
    {
      name: 'acceptDescription',
      label: 'Accept Description',
      dataType: 'string',
      defaultValue: 'All files accepted',
      controlType: 'text_input',
      group: 'appearance',
      order: 5,
    },
  ],

  image_upload: [
    {
      name: 'allowedTypes',
      label: 'Allowed Image Types',
      dataType: 'array',
      defaultValue: ['image/jpeg', 'image/png', 'image/gif'],
      controlType: 'multi_select',
      options: [
        { value: 'image/jpeg', label: 'JPEG' },
        { value: 'image/png', label: 'PNG' },
        { value: 'image/gif', label: 'GIF' },
        { value: 'image/webp', label: 'WebP' },
        { value: 'image/svg+xml', label: 'SVG' },
      ],
      group: 'validation',
      order: 1,
    },
    {
      name: 'maxFileSize',
      label: 'Max File Size (MB)',
      dataType: 'number',
      defaultValue: 5,
      controlType: 'number_input',
      validation: { min: 0.1, max: 50 },
      group: 'validation',
      order: 2,
    },
    {
      name: 'multiple',
      label: 'Allow Multiple Images',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 1,
    },
    {
      name: 'maxImages',
      label: 'Maximum Images',
      dataType: 'number',
      defaultValue: 5,
      controlType: 'number_input',
      validation: { min: 1, max: 20 },
      showWhen: { attribute: 'multiple', operator: 'equals', value: true },
      group: 'behavior',
      order: 2,
    },
    {
      name: 'enableCrop',
      label: 'Enable Cropping',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'behavior',
      order: 3,
    },
    {
      name: 'cropAspectRatio',
      label: 'Crop Aspect Ratio',
      description: 'e.g., 1.77 for 16:9',
      dataType: 'number',
      defaultValue: undefined,
      controlType: 'number_input',
      showWhen: { attribute: 'enableCrop', operator: 'equals', value: true },
      group: 'behavior',
      order: 4,
    },
    {
      name: 'compress',
      label: 'Compress Images',
      dataType: 'boolean',
      defaultValue: false,
      controlType: 'toggle',
      group: 'advanced',
      order: 1,
    },
    {
      name: 'compressionQuality',
      label: 'Compression Quality',
      dataType: 'number',
      defaultValue: 0.8,
      controlType: 'slider',
      validation: { min: 0.1, max: 1 },
      showWhen: { attribute: 'compress', operator: 'equals', value: true },
      group: 'advanced',
      order: 2,
    },
    {
      name: 'showPreview',
      label: 'Show Preview',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'appearance',
      order: 1,
    },
    {
      name: 'previewSize',
      label: 'Preview Size',
      dataType: 'string',
      defaultValue: 'medium',
      controlType: 'dropdown',
      options: [
        { value: 'small', label: 'Small' },
        { value: 'medium', label: 'Medium' },
        { value: 'large', label: 'Large' },
      ],
      showWhen: { attribute: 'showPreview', operator: 'equals', value: true },
      group: 'appearance',
      order: 2,
    },
  ],

  signature: [
    {
      name: 'canvasWidth',
      label: 'Canvas Width',
      dataType: 'number',
      defaultValue: 400,
      controlType: 'number_input',
      validation: { min: 200, max: 800 },
      group: 'appearance',
      order: 1,
    },
    {
      name: 'canvasHeight',
      label: 'Canvas Height',
      dataType: 'number',
      defaultValue: 200,
      controlType: 'number_input',
      validation: { min: 100, max: 400 },
      group: 'appearance',
      order: 2,
    },
    {
      name: 'strokeColor',
      label: 'Stroke Color',
      dataType: 'string',
      defaultValue: '#000000',
      controlType: 'color_picker',
      group: 'appearance',
      order: 3,
    },
    {
      name: 'strokeWidth',
      label: 'Stroke Width',
      dataType: 'number',
      defaultValue: 2,
      controlType: 'slider',
      validation: { min: 1, max: 5 },
      group: 'appearance',
      order: 4,
    },
    {
      name: 'backgroundColor',
      label: 'Background Color',
      dataType: 'string',
      defaultValue: '#FFFFFF',
      controlType: 'color_picker',
      group: 'appearance',
      order: 5,
    },
    {
      name: 'showClear',
      label: 'Show Clear Button',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'behavior',
      order: 1,
    },
    {
      name: 'allowTyped',
      label: 'Allow Typed Signature',
      dataType: 'boolean',
      defaultValue: true,
      controlType: 'toggle',
      group: 'behavior',
      order: 2,
    },
    {
      name: 'outputFormat',
      label: 'Output Format',
      dataType: 'string',
      defaultValue: 'png',
      controlType: 'dropdown',
      options: [
        { value: 'png', label: 'PNG Image' },
        { value: 'svg', label: 'SVG Vector' },
        { value: 'base64', label: 'Base64 String' },
      ],
      group: 'advanced',
      order: 1,
    },
  ],

  // Stub schemas for remaining types
  matrix: [],
  ranking: [],
  address: [],
  tags: [],
  color_picker: [],
  payment: [],
  opinion_scale: [],
};

// ============================================
// Question Type Metadata
// ============================================

export const questionTypeMetadata: Record<QuestionTypeId, QuestionTypeMetadata> = {
  short_text: {
    id: 'short_text',
    displayName: 'Short Answer',
    description: 'Single line text input',
    category: 'text_input',
    icon: 'TextFields',
    bsonType: 'string',
    attributeSchemas: attributeSchemas.short_text,
    tags: ['text', 'input', 'basic', 'string'],
  },
  long_text: {
    id: 'long_text',
    displayName: 'Paragraph',
    description: 'Multi-line text area for longer responses',
    category: 'text_input',
    icon: 'Notes',
    bsonType: 'string',
    attributeSchemas: attributeSchemas.long_text,
    tags: ['text', 'textarea', 'paragraph', 'long'],
  },
  number: {
    id: 'number',
    displayName: 'Number',
    description: 'Numeric input with optional formatting',
    category: 'text_input',
    icon: 'Numbers',
    bsonType: 'number',
    attributeSchemas: attributeSchemas.number,
    tags: ['number', 'numeric', 'integer', 'decimal'],
  },
  email: {
    id: 'email',
    displayName: 'Email',
    description: 'Email address with validation',
    category: 'text_input',
    icon: 'Email',
    bsonType: 'string',
    attributeSchemas: attributeSchemas.email,
    tags: ['email', 'contact', 'validation'],
  },
  phone: {
    id: 'phone',
    displayName: 'Phone',
    description: 'Phone number with country code',
    category: 'text_input',
    icon: 'Phone',
    bsonType: 'string',
    attributeSchemas: attributeSchemas.phone,
    tags: ['phone', 'telephone', 'contact'],
  },
  url: {
    id: 'url',
    displayName: 'Website URL',
    description: 'Web address input',
    category: 'text_input',
    icon: 'Link',
    bsonType: 'string',
    attributeSchemas: attributeSchemas.url,
    tags: ['url', 'link', 'website', 'web'],
  },
  multiple_choice: {
    id: 'multiple_choice',
    displayName: 'Multiple Choice',
    description: 'Select one option from a list',
    category: 'choice',
    icon: 'RadioButtonChecked',
    bsonType: 'string',
    attributeSchemas: attributeSchemas.multiple_choice,
    tags: ['choice', 'radio', 'single', 'select'],
  },
  checkboxes: {
    id: 'checkboxes',
    displayName: 'Checkboxes',
    description: 'Select multiple options',
    category: 'choice',
    icon: 'CheckBox',
    bsonType: 'array',
    attributeSchemas: attributeSchemas.checkboxes,
    tags: ['checkbox', 'multi', 'multiple', 'select'],
  },
  dropdown: {
    id: 'dropdown',
    displayName: 'Dropdown',
    description: 'Select from a dropdown menu',
    category: 'choice',
    icon: 'ArrowDropDownCircle',
    bsonType: 'string',
    attributeSchemas: attributeSchemas.dropdown,
    tags: ['dropdown', 'select', 'menu', 'lookup'],
  },
  yes_no: {
    id: 'yes_no',
    displayName: 'Yes/No',
    description: 'Simple yes or no choice',
    category: 'choice',
    icon: 'ToggleOn',
    bsonType: 'bool',
    attributeSchemas: attributeSchemas.yes_no,
    tags: ['boolean', 'toggle', 'yes', 'no', 'binary'],
  },
  rating: {
    id: 'rating',
    displayName: 'Rating',
    description: 'Star or icon-based rating',
    category: 'rating_scale',
    icon: 'Star',
    bsonType: 'number',
    attributeSchemas: attributeSchemas.rating,
    tags: ['rating', 'stars', 'score', 'review'],
  },
  scale: {
    id: 'scale',
    displayName: 'Linear Scale',
    description: 'Numeric scale (e.g., 1-10)',
    category: 'rating_scale',
    icon: 'LinearScale',
    bsonType: 'number',
    attributeSchemas: attributeSchemas.scale,
    tags: ['scale', 'linear', 'likert', 'range'],
  },
  slider: {
    id: 'slider',
    displayName: 'Slider',
    description: 'Drag to select a value',
    category: 'rating_scale',
    icon: 'Tune',
    bsonType: 'number',
    attributeSchemas: attributeSchemas.slider,
    tags: ['slider', 'range', 'drag', 'continuous'],
  },
  nps: {
    id: 'nps',
    displayName: 'Net Promoter Score',
    description: 'Industry-standard NPS question',
    category: 'rating_scale',
    icon: 'TrendingUp',
    bsonType: 'number',
    attributeSchemas: attributeSchemas.nps,
    tags: ['nps', 'promoter', 'loyalty', 'satisfaction'],
  },
  opinion_scale: {
    id: 'opinion_scale',
    displayName: 'Opinion Scale',
    description: 'Likert-style agreement scale',
    category: 'rating_scale',
    icon: 'SentimentSatisfied',
    bsonType: 'number',
    attributeSchemas: attributeSchemas.opinion_scale,
    tags: ['opinion', 'likert', 'agreement', 'satisfaction'],
  },
  date: {
    id: 'date',
    displayName: 'Date',
    description: 'Date picker',
    category: 'date_time',
    icon: 'CalendarMonth',
    bsonType: 'date',
    attributeSchemas: attributeSchemas.date,
    tags: ['date', 'calendar', 'day', 'month', 'year'],
  },
  time: {
    id: 'time',
    displayName: 'Time',
    description: 'Time picker',
    category: 'date_time',
    icon: 'AccessTime',
    bsonType: 'string',
    attributeSchemas: attributeSchemas.time,
    tags: ['time', 'clock', 'hour', 'minute'],
  },
  datetime: {
    id: 'datetime',
    displayName: 'Date & Time',
    description: 'Combined date and time picker',
    category: 'date_time',
    icon: 'Event',
    bsonType: 'date',
    attributeSchemas: attributeSchemas.datetime,
    tags: ['datetime', 'timestamp', 'schedule'],
  },
  file_upload: {
    id: 'file_upload',
    displayName: 'File Upload',
    description: 'Upload files of any type',
    category: 'media_upload',
    icon: 'AttachFile',
    bsonType: 'object',
    attributeSchemas: attributeSchemas.file_upload,
    tags: ['file', 'upload', 'attachment', 'document'],
  },
  image_upload: {
    id: 'image_upload',
    displayName: 'Image Upload',
    description: 'Upload and preview images',
    category: 'media_upload',
    icon: 'Image',
    bsonType: 'object',
    attributeSchemas: attributeSchemas.image_upload,
    tags: ['image', 'photo', 'picture', 'upload'],
  },
  signature: {
    id: 'signature',
    displayName: 'Signature',
    description: 'Capture handwritten signature',
    category: 'media_upload',
    icon: 'Draw',
    bsonType: 'string',
    attributeSchemas: attributeSchemas.signature,
    tags: ['signature', 'sign', 'handwriting', 'legal'],
  },
  matrix: {
    id: 'matrix',
    displayName: 'Matrix / Grid',
    description: 'Table-style question grid',
    category: 'advanced',
    icon: 'GridOn',
    bsonType: 'object',
    attributeSchemas: attributeSchemas.matrix,
    tags: ['matrix', 'grid', 'table', 'rows', 'columns'],
  },
  ranking: {
    id: 'ranking',
    displayName: 'Ranking',
    description: 'Drag to rank items in order',
    category: 'advanced',
    icon: 'FormatListNumbered',
    bsonType: 'array',
    attributeSchemas: attributeSchemas.ranking,
    tags: ['ranking', 'order', 'priority', 'sort'],
  },
  address: {
    id: 'address',
    displayName: 'Address',
    description: 'Full address input with autocomplete',
    category: 'specialized',
    icon: 'LocationOn',
    bsonType: 'object',
    attributeSchemas: attributeSchemas.address,
    tags: ['address', 'location', 'street', 'city', 'country'],
  },
  tags: {
    id: 'tags',
    displayName: 'Tags',
    description: 'Add multiple tags or keywords',
    category: 'specialized',
    icon: 'LocalOffer',
    bsonType: 'array',
    attributeSchemas: attributeSchemas.tags,
    tags: ['tags', 'keywords', 'labels', 'chips'],
  },
  color_picker: {
    id: 'color_picker',
    displayName: 'Color Picker',
    description: 'Select a color value',
    category: 'specialized',
    icon: 'Palette',
    bsonType: 'string',
    attributeSchemas: attributeSchemas.color_picker,
    tags: ['color', 'picker', 'hex', 'rgb'],
  },
  payment: {
    id: 'payment',
    displayName: 'Payment',
    description: 'Collect payment information',
    category: 'specialized',
    icon: 'Payment',
    bsonType: 'object',
    attributeSchemas: attributeSchemas.payment,
    tags: ['payment', 'money', 'credit', 'stripe'],
    premium: true,
  },
};

// ============================================
// Factory Functions
// ============================================

/**
 * Create a new question with default values
 */
export function createQuestion<T extends QuestionTypeId>(
  type: T,
  overrides: Partial<Question> = {}
): Question {
  const metadata = questionTypeMetadata[type];
  const defaults = defaultAttributes[type];

  const base = {
    id: generateId(),
    type,
    path: '',
    label: metadata.displayName,
    description: '',
    placeholder: '',
    required: false,
    included: true,
    source: 'custom' as const,
    includeInDocument: true,
    conditionalLogic: undefined,
    validation: undefined,
    modeConfig: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    attributes: { ...defaults },
    ...overrides,
  };

  return base as Question;
}

/**
 * Get default attributes for a question type
 */
export function getDefaultAttributes(type: QuestionTypeId) {
  return { ...defaultAttributes[type] };
}

/**
 * Get metadata for a question type
 */
export function getQuestionTypeMetadata(type: QuestionTypeId): QuestionTypeMetadata {
  return questionTypeMetadata[type];
}

/**
 * Get all question types by category
 */
export function getQuestionTypesByCategory(): Record<QuestionCategory, QuestionTypeMetadata[]> {
  const byCategory: Record<QuestionCategory, QuestionTypeMetadata[]> = {
    text_input: [],
    choice: [],
    rating_scale: [],
    date_time: [],
    media_upload: [],
    advanced: [],
    specialized: [],
  };

  Object.values(questionTypeMetadata).forEach((meta) => {
    byCategory[meta.category].push(meta);
  });

  return byCategory;
}

/**
 * Search question types by query
 */
export function searchQuestionTypes(query: string): QuestionTypeMetadata[] {
  const lowerQuery = query.toLowerCase();
  return Object.values(questionTypeMetadata).filter(
    (meta) =>
      meta.displayName.toLowerCase().includes(lowerQuery) ||
      meta.description.toLowerCase().includes(lowerQuery) ||
      meta.tags.some((tag) => tag.includes(lowerQuery))
  );
}

// ============================================
// Validation Functions
// ============================================

/**
 * Validate question-specific attributes
 */
export function validateQuestion(question: Question): ValidationResult {
  const errors: ValidationResult['errors'] = [];
  const schemas = attributeSchemas[question.type] || [];

  // Validate each attribute against its schema
  for (const schema of schemas) {
    const value = (question as any).attributes?.[schema.name];

    // Check required
    if (schema.validation?.required && (value === undefined || value === null || value === '')) {
      errors.push({
        field: `attributes.${schema.name}`,
        message: `${schema.label} is required`,
        code: 'required',
      });
    }

    // Check min/max for numbers
    if (typeof value === 'number') {
      if (schema.validation?.min !== undefined && value < schema.validation.min) {
        errors.push({
          field: `attributes.${schema.name}`,
          message: `${schema.label} must be at least ${schema.validation.min}`,
          code: 'min',
        });
      }
      if (schema.validation?.max !== undefined && value > schema.validation.max) {
        errors.push({
          field: `attributes.${schema.name}`,
          message: `${schema.label} must be at most ${schema.validation.max}`,
          code: 'max',
        });
      }
    }

    // Check minLength/maxLength for strings
    if (typeof value === 'string') {
      if (schema.validation?.minLength !== undefined && value.length < schema.validation.minLength) {
        errors.push({
          field: `attributes.${schema.name}`,
          message: `${schema.label} must be at least ${schema.validation.minLength} characters`,
          code: 'minLength',
        });
      }
      if (schema.validation?.maxLength !== undefined && value.length > schema.validation.maxLength) {
        errors.push({
          field: `attributes.${schema.name}`,
          message: `${schema.label} must be at most ${schema.validation.maxLength} characters`,
          code: 'maxLength',
        });
      }
    }

    // Check pattern
    if (schema.validation?.pattern && typeof value === 'string') {
      const regex = new RegExp(schema.validation.pattern);
      if (!regex.test(value)) {
        errors.push({
          field: `attributes.${schema.name}`,
          message: `${schema.label} format is invalid`,
          code: 'pattern',
        });
      }
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

// ============================================
// Registry Export
// ============================================

export const questionTypeRegistry = {
  metadata: questionTypeMetadata,
  defaults: defaultAttributes,
  schemas: attributeSchemas,
  create: createQuestion,
  getMetadata: getQuestionTypeMetadata,
  getDefaults: getDefaultAttributes,
  getByCategory: getQuestionTypesByCategory,
  search: searchQuestionTypes,
  validate: validateQuestion,
};

export default questionTypeRegistry;
